### ISSUE TITLE
Autocomplete a no show

### ISSUE THREAD

**Issue by dylannirvana** [tamino-martinius/atom-language-spacebars#3]
If, each and template code completion unfortunately not working. For example, typing "if" doesn't bring up the Spacebars syntax. None of the double curly brace comes up as a shortcut.

**Comment by tamino-martinius** [comment]
A bit late, but this should be fixed now with `v0.3.1` - looks like the language scope was `.text.html` when Spacebars got auto detected for `.html` files and `.text.html.spacebars` was just used when explicitly set
