### ISSUE TITLE
Could you build this for VS Code?

### ISSUE THREAD

**Issue by RTSchriner** [tamino-martinius/atom-language-spacebars#4]
One of the things I miss from Atom is this plugin. As a Meteor developer, who still uses Blaze(Spacebars), this would be a huge help in VS Code.

Love the plugin, thanks!

**Comment by tamino-martinius** [comment]
Hi thanks for that request - actually i switched to VS Code on my own recently - so i will definitely check that out

**Comment by RTSchriner** [comment]
I'm not experienced in making language plugins, but let me know if you need any help.

**Comment by tamino-martinius** [comment]
It turns out that it wasn't hard to convert.

Code: https://github.com/tamino-martinius/vscode-language-spacebars
Extension: https://marketplace.visualstudio.com/items?itemName=tamino-martinius.spacebars

**Comment by RTSchriner** [comment]
@tamino-martinius: You rock! 🎸
